

server:
  port: 8564
  db:
    host: ${DB_HOST:172.24.49.78}
    port: ${DB_PORT:15432}
    name: ${DB_DATABASE:iot_gps}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  redis:
    host: ${REDIS_HOST:IP}
    port: ${REDIS_PORT:PORT}
  mqtt:
    host: ${MQTT_HOST:tcp://127.0.0.1:1883}
    user-name: ${MQTT_USERNAME:admin}
    password: ${MQTT_PASSWORD:admin@123.}
    client-id: ${MQTT_CLIENT_ID:backend-server}
    topic: ${MQTT_TOPIC:esp32/data}
  servlet:
    context-path: /api

storage:
  web-base-url: https://admcc.cn
  src: ${USER_SAVE:/src}
  type: Local


thread:
  core: 5
  max: 10


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  lazy-initialization:
  global-config:
    db-config:
      # 全局配置已经删除的值
      logic-delete-value: 1
      # 全局配置未删除的值
      logic-not-delete-value: 0
  configuration:
    ##日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

spring:
  profiles:
    avtive: '@build.profile.id@'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${server.db.host}:${server.db.port}/${server.db.name}
    username: ${server.db.user}
    password: ${server.db.password}
  servlet:
    multipart:
      enabled: true
      # 单个文件的最大值
      max-file-size: 51200MB
      # 上传文件总的最大值
      max-request-size: 512000MB
  data:
    redis:
      jedis:
        pool:
          min-idle: 0
          max-idle: 8
      host: ${server.redis.host}
      port: ${server.redis.port}
      password:
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtps
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: xxx@163.com
    #授权码
    password: xxx
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    templateConfig: html/email-template.html


# 物联网访问端口
tcp:
  port: 8000

## mq配置
mqtt:
  host:  ${server.mqtt.host}
  user-name: ${server.mqtt.user-name}
  password: ${server.mqtt.password}
  client-id: ${server.mqtt.client-id}
  topic: ${server.mqtt.topic}
  keepAlive: 30

## 高德的配置
gd:
  api-token: 940ce1ea6a9b829869dca515eed2de33
  baseUrl: https://restapi.amap.com
