
spring:
  profiles:
    active: '@build.profile.id@'

sa-token:
  token-name: authentication
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid

# 数据加密
security:
  publicKeyPath: ${PUBLIC_KEY_PATH:E:\code_project\gps_iost\api-service\src\main\resources\public_key.pem}
  privateKeyPath: ${PRIVATE_PATH:E:\code_project\gps_iost\api-service\src\main\resources\private_key.pem}


cors:
  enabled: true